language: rust
rust: nightly
sudo: false

os:
    - linux
    - osx

script:
    - cargo build --verbose
    # We can't build this since it requires a modern gcc
    # compiler to build libazure, and travis does not support it
    # - cargo build --features texture_surface --verbose
