language: rust
rust: nightly
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libxxf86vm-dev
      - libosmesa6-dev
      - libgles2-mesa-dev
      - gcc-arm-linux-androideabi

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8; rustup target add arm-linux-androideabi; fi

os:
  - linux
  - osx

script:
  - cargo build --verbose
  # TODO: tests
  # - cargo test --verbose
  # - cargo test --verbose --features test_egl_in_linux

