language: rust
rust: nightly
sudo: false

os:
    - linux
    - osx

# Needed to build some deps
compiler: gcc

script:
    - cargo build --verbose
    - cargo build --features texture_surface --verbose
