[package]

name = "offscreen_gl_context"
version = "0.0.1"
authors = ["ecoal95 <ecoal95@gmail.com>"]

[dependencies]
libc = "*"

[dependencies.glx]
git = "https://github.com/servo/rust-glx"

[dependencies.xlib]
git = "https://github.com/servo/rust-xlib"

[dependencies.cgl]
git = "https://github.com/servo/rust-cgl"

[dependencies.gleam]
git = "https://github.com/servo/gleam"

[dependencies.geom]
git = "https://github.com/servo/rust-geom"
