[package]
name = "offscreen_gl_context"
license = "MIT / Apache-2.0"
version = "0.1.0"
authors = ["ecoal95 <ecoal95@gmail.com>", "The Servo Project Developers"]
description = "Creation and manipulation of HW accelerated offscreen rendering contexts in multiple platforms. Originally intended for the Servo project WebGL implementation."
repository = "https://github.com/ecoal95/rust-offscreen-rendering-context"
build = "build.rs"

[build-dependencies]
gl_generator = "0.0.28"
khronos_api = "0.0.8"

[features]
texture_surface = ["layers"]

[dependencies]
libc = "*"
log  = "*"
gleam = "0.1"
euclid = "0.3"
serde = "*"
serde_macros = "*"

[dependencies.layers]
git = "https://github.com/servo/rust-layers"
optional = true

[target.x86_64-apple-darwin.dependencies]
core-foundation = "*"
cgl = "0.1"

[target.i686-unknown-linux-gnu.dependencies.x11]
version = "^2.0.1"
features = ["xlib"]

[target.x86_64-unknown-linux-gnu.dependencies.x11]
version = "^2.0.1"
features = ["xlib"]

[target.arm-unknown-linux-gnueabihf.dependencies.x11]
version = "^2.0.1"
features = ["xlib"]

[target.aarch64-unknown-linux-gnu.dependencies.x11]
version = "^2.0.1"
features = ["xlib"]

[target.x86_64-pc-windows-gnu.dependencies]
glutin = "*"
